### ISSUE TITLE
How are the payouts of off chain apps calculated?

### ISSUE THREAD

**Issue by Kinthrowaway** [kinecosystem/kin-rewards-engine#1]
Some apps that are being paid from the KRE are not on the Kin blockchain and instead I have read that they are being relayed on to the Kin blockchain through a service of some kind however I am not seeing any logic for this.

Where are you pulling their data from? 
How are their payouts calculated?

**Comment by kikengineering** [comment]
Hi there,
We're not exactly sure what apps you are referring to, but all of our activity data comes directly from the Kin blockchain.
Could you be more specific about this service?

**Comment by Kinthrowaway** [comment]
Hi,

I am referring to Madlipz they have account creations appearing on the Kin blockchain but no Kin transfers (earn/spends) https://kin-bubbles.herokuapp.com/?show=lipz. P365 appears to be the same https://kin-bubbles.herokuapp.com/?show=p365. This service is pulling data from the Kin blockchain through Horizon https://horizon-block-explorer.kininfrastructure.com/

Just to make sure I used the B&R in Madlipz and the account I created had no balance or Kin history when it should have as I have been using the account and earning/spending with it when I view it using the official Kin explorer.

**Comment by kikengineering** [comment]
Ahh right.
Those apps are still using the Kin2 blockchain. Kin Bubbles only looks at Kin3 so they wouldn't be on there. The KRE collects data from both, aggregates and calculates payouts accordingly (i.e. the view '[payments_and_creates_view](https://github.com/kinecosystem/kin-rewards-engine/blob/master/schemas/stellar/payments_and_creates_view.json)' in the code contains information from both blockchains). Unfortunately, there is no simple explorer for the Kin2 blockchain other than querying horizon directly.

**Comment by Kinthrowaway** [comment]
It was my understanding that Kin3 is the Kin blockchain, what is the Kin2 blockchain and how is communication between the 2 handled? Just to clarify that the data used to calculate KRE payouts doesn't solely originate from the Kin blockchain? Can you provide a data source for apps that are using the Kin2 blockchain so KRE payouts can be calculated/verified by an independent?

**Comment by kikengineering** [comment]
These blockchains are separate. They don't communicate with each other. The KRE simply collects data from both and verifies earns and spends from each of them separately.
You can check an account on Kin2 by going here:
https://horizon-kin-ecosystem.kininfrastructure.com/accounts/ "public key here"

**Comment by Kinthrowaway** [comment]
Thank you for the clarification the medium post and your response made it out like there is only 1 Kin blo
